spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SpringProducts?serverTimezone=Europe/Warsaw&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

